version: '3.9'

services:

  database:
    image: mongo:latest
    container_name: mongoDBContainer
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    env_file:
      - .env
    volumes:
      - db:/data/db
volumes:
  db:
    driver: local